# Generated by Django 4.0.5 on 2022-07-20 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('img', models.ImageField(upload_to='news/')),
                ('views', models.IntegerField(default=0)),
                ('is_main', models.BooleanField(default=False)),
                ('is_editor_choice', models.BooleanField(default=False)),
                ('is_trend', models.BooleanField(default=False)),
                ('is_interview', models.BooleanField(default=False)),
                ('is_investigation', models.BooleanField(default=False)),
                ('is_article', models.BooleanField(default=False)),
                ('is_business', models.BooleanField(default=False)),
                ('is_videonews', models.BooleanField(default=False)),
                ('is_photonews', models.BooleanField(default=False)),
                ('is_adviced', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kunuz.category')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kunuz.city')),
                ('tags', models.ManyToManyField(blank=True, null=True, related_name='news', to='kunuz.tag')),
            ],
        ),
    ]
