# Generated by Django 4.0.5 on 2022-07-20 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kunuz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='news', to='kunuz.tag'),
        ),
    ]
